name: CI

on: 
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run Vitest tests
        run: yarn test
