name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
     steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
    - name: yarn install
      run: |
        yarn install
    - name: yarn test
      run: |
        yarn test 
      env:
        CI: true
      
    - name: yarn build
      run: |
        yarn run build --if-present